### ISSUE TITLE
Depend directly on Microsoft.SqlServer.TransactSql.ScriptDom nuget package

### ISSUE THREAD

**Issue by oconnor0** [xledger/Xledger.Sql#1]
I don't believe this needs the full Microsoft.SqlServer.DacFx dependency and now that Microsoft has published the ScriptDom as a standalone nuget package https://www.nuget.org/packages/Microsoft.SqlServer.TransactSql.ScriptDom, it probably makes sense to move to that.

**Comment by isaksky** [comment]
Yea I don't think we need anything else, that is great news.

**Comment by oconnor0** [comment]
We could probably publish 1.0 with this change too.

**Comment by isaksky** [comment]
Yea good idea.
